version: "3.0"
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /root/link_api/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=_PG_USER_
      - POSTGRES_PASSWORD=_PG_PASSWORD_
      - POSTGRES_DB=_PG_DB_
    networks: [ 'mynetwork' ]

  link-api:
    image: registry.gitlab.com/diak312/link_api:main
    restart: always
    ports:
      - 80:80
      - 3050:3050
    depends_on:
      - db
    networks: ['mynetwork']
    env_file:
      - .env
    volumes:
      - ./.env:/dist/.env

networks: {mynetwork: {}}